# Generated by Django 3.2.9 on 2022-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isdoner',
            field=models.BooleanField(default=False),
        ),
    ]
