# Generated by Django 3.2.9 on 2022-01-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_customuser_isdoner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isdoner',
        ),
    ]
