# Generated by Django 3.2.9 on 2022-01-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_auto_20220111_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isDonator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
    ]
