# Generated by Django 3.2.9 on 2022-01-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_auto_20220110_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isDonator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
